server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${BALDWARS_DB_URL}
    username: ${BALDWARS_DB_USER}
    password: ${BALDWARS_DB_PASSWORD}

security:
  token:
    secret: Bearer ${JWT_TOKEN_SECRET}

logging:
  level:
    org:
      springframework:
        security: error
