server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

          # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#          spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false

          # Because detection is disabled you have to set correct dialect by hand.
#          spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    username: ${BALDWARS_DB_USER}
    password: ${BALDWARS_DB_PASSWORD}
    url: ${BALDWARS_DB_URL}

security:
  token:
    secret: ${JWT_TOKEN_SECRET}

logging:
  level:
    org:
      springframework:
        security: error
