server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    username: ${BALDWARS_DB_USER}
    password: ${BALDWARS_DB_PASSWORD}
    url: ${BALDWARS_DB_URL}

security:
  token:
    secret: ${JWT_TOKEN_SECRET}

logging:
  level:
    org:
      springframework:
        security: error
