server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
<<<<<<< HEAD
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
=======
    url: jdbc:${BALDWARS_DB_URL}/${BALDWARS_DB_NAME}
    username: ${BALDWARS_DB_USER}
    password: ${BALDWARS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
>>>>>>> cb134a6 (Change config app.)

security:
  token:
    secret: ${JWT_TOKEN_SECRET}

logging:
  level:
    org:
      springframework:
        security: error
